- name: Install dependencies
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - build-essential
      - python3-pip
    state: present
    update-cache: yes

- name: Download Docker GPG key
  get_url:
    url: "https://download.docker.com/{{ ansible_system|lower }}/{{ ansible_distribution|lower }}/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0644"
  become: true

- name: Import Docker GPG key
  command: gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg /etc/apt/trusted.gpg.d/docker.asc
  become: true
  args:
    creates: /etc/apt/trusted.gpg.d/docker.gpg

- name: Remove the ASCII Docker GPG key
  file:
    path: /etc/apt/trusted.gpg.d/docker.asc
    state: absent
  become: true

- name: Add docker repo
  become: true
  apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}] https://download.docker.com/{{ ansible_system|lower }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Add gitlab-runner user to docker group
  become: true
  user:
    name: gitlab-runner
    append: yes
    groups: docker

- name: Install rust
  become: true
  args:
    creates: /usr/bin/rustc
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: Install gitlab runner
  become: true
  get_url:
    url: "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64"
    dest: /usr/bin/gitlab-runner
    mode: "0744"

- name: Install gitlab runner home
  become: true
  command: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner

- name: Run gitlab runners
  become: true
  command: |
    gitlab-runner start

- name: Register gitlab docker runner
  become: true
  command: |
    gitlab-runner register \
    --non-interactive \
    --url "https://git.foobar.vip/" \
    --token "{{ reg_token_docker }}" \
    --executor "docker" \
    --docker-image alpine:latest

- name: Register gitlab shell runner
  become: true
  command: |
    gitlab-runner register \
    --non-interactive \
    --url "https://git.foobar.vip/" \
    --token "{{ reg_token_shell }}" \
    --executor "shell"
