---
# domain_internal: sharedien.internal
# domain_public: sharedien.systems
base_packages_apt_early: [gpg]
base_packages_apt:
  - apt-transport-https
  - ca-certificates
  - curl
  - fish
  - gnupg-agent
  - ripgrep
  - auditd
  - software-properties-common
base_packages_pip:
locale_list:
  - de_CH ISO-8859-1
  - de_CH.UTF-8 UTF-8
  - de_DE ISO-8859-1
  - de_DE.UTF-8 UTF-8
  - de_DE@euro ISO-8859-15
  - en_US ISO-8859-1
  - en_US.ISO-8859-15 ISO-8859-15
  - en_US.UTF-8 UTF-8
# groups:
#  - { name: git, gid: 5000 }

# Example:
# users:
#   - { name: doe.j, uid: 10000, comment: "John Doe", email: "john.doe@advellence.com", shell: "/bin/sh", groups: [adm, sudo, users], public_keys: "ssh-rsa …" }
users_remove:
