---
- hosts: servers
  gather_facts: true
  roles:
    - general
    - docker

- hosts: gitlab
  gather_facts: true
  roles:
    - general
    - gitlab
# - hosts: vpn_hosts
#   gather_facts: true
#   roles:
#     - general
#     - docker
#     - bastion
