# community.docker.docker_compose requires Docker SDK for Python (pip) on destination host

# - name: Take wireguard container down
#   community.docker.docker_compose:
#     project_src: "{{ wireguard_dir }}"
#     state: absent
#   become: true
#   become_user: shradmin

# - name: Take wireguard container up
#   community.docker.docker_compose:
#     project_src: "{{ wireguard_dir }}"
#     state: present
#   become: true
#   become_user: shradmin

- name: Take wireguard container down
  ansible.builtin.command:
    chdir: "{{ wireguard_dir }}"
    cmd: docker-compose down
  become: true
  become_user: shradmin

- name: Take wireguard container up
  ansible.builtin.command:
    chdir: "{{ wireguard_dir }}"
    cmd: docker-compose up -d
  become: true
  become_user: shradmin
