- name: Remove the nano and vi packages
  ansible.builtin.package:
    name:
      - nano
      - vim
      - vim-common
      - vim-runtime
      - vim-tiny
    state: absent
  tags: packages
  become: true
- name: Install vim
  ansible.builtin.package:
    name:
      - vim
    state: present
  tags: packages
  become: true
- name: Add vim alternatives
  community.general.alternatives:
    link: "/usr/bin/{{ item }}"
    name: "{{ item }}"
    path: /usr/bin/vim
    priority: 110
  tags: packages
  become: true
  loop:
    - vimdiff
