- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: packages
  become: true

- name: Install some very few extra basic packages early
  ansible.builtin.apt:
    name: "{{ base_packages_apt_early }}"
    update_cache: true
  tags: packages
  become: true

- name: Add APT keys
  ansible.builtin.apt_key:
    url: "{{ item }}"
  tags: packages
  become: true
  loop: "{{ apt_key_urls | default([]) }}"

- name: Add repos
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  tags: packages
  become: true
  loop: "{{ apt_repos_list | default([]) }}"

- name: Install some basic packages
  ansible.builtin.apt:
    name: "{{ base_packages_apt }}"
    update_cache: true
  tags: packages
  become: true

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true
  tags: packages
  become: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
  tags: packages
  become: true
