- name: Custom SSH Config
  ansible.builtin.copy:
    src: ssh/sshd_config
    dest: /etc/ssh/sshd_config.d/98-customssh.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Ensure sshd config is reloaded
  become: true
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    state: restarted
