- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present
  become: true

- name: Allow custom SSH
  become: true
  community.general.ufw:
    rule: allow
    port: '10000'
    proto: tcp
    state: enabled

- name: Allow HTTP
  become: true
  community.general.ufw:
    rule: allow
    port: '80'
    state: enabled

- name: Allow HTTPS
  become: true
  community.general.ufw:
    rule: allow
    port: '443'
    state: enabled

- name: Disallow Default Access on any other Port
  become: true
  community.general.ufw:
    rule: allow
    port: '443'
    state: enabled

- name: Rate Limit SSH
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Ensure ufw is enabled and running
  become: true
  ansible.builtin.systemd:
    name: ufw
    enabled: yes
    state: started
