- name: Add APT keys
  ansible.builtin.apt_key:
    url: "{{ item }}"
  tags: packages
  become: true
  loop: "{{ apt_key_urls }}"
- name: Add repos
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  tags: packages
  become: true
  loop: "{{ apt_repos_list }}"
- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ pkgs }}"
    update_cache: true
  tags: packages
  become: true
- name: Install helper scripts
  ansible.builtin.copy:
    src: "files/scripts/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop:
    - docker-container-running.sh
  become: true
- name: Add shradmin user to docker group
  ansible.builtin.user:
    name: shradmin
    groups: docker
    append: true
  tags: users
  become: true
- name: Add container user to docker group
  ansible.builtin.user:
    name: container
    groups: docker
    append: true
  tags: users
  become: true
